theme: jekyll-theme-hacker
title: William Hopton's homepage
description: This is my Portfolio of the work I have completed during University. I have just completed my final year in a Games Programming course at the University of Gloucestershire. I am well versed in Unity and Unreal Engine 5 development using C# and C++.
description: My projects are on GitHub which I have linked below.

layout: page
title: "TestNewThis"
permalink: https://yuzu2005.github.io/404.html
